### ISSUE TITLE
Is scrypt working?

### ISSUE THREAD

**Issue by domalaq** [EdgeApp/react-native-fast-crypto#1]
Hi! I tried to use your module in my app, but it returns error. I wonder if this is already working library.

**Comment by swansontec** [comment]
We do have scrypt working in our app. The parameters to the function are: `scrypt (data: Uint8Array, salt: Uint8Array, n: number, r: number, p: number, outLength: number) => Promise<Uint8Array>`. If you need to do scrypt on strings, you need to convert them to UTF-8 first. There are [good reasons](https://www.npmjs.com/package/scrypt-js#encoding-notes) for this.

**Comment by paullinator** [comment]
This does not yet work in Android. Just iOS but Android is coming soon.

**Comment by domalaq** [comment]
Oh I see. I am trying to use it on Android. Thanks.
This is a great module you're doing!

**Comment by paullinator** [comment]
Thanks. We're excited about it too. We hope to make it fully compatible with nodejs `crypto` but it may take awhile.

**Comment by paullinator** [comment]
Android is now fully working alongside iOS for all the exported crypto routines.
