### ISSUE TITLE
PBKDF2 Documentation

### ISSUE THREAD

**Issue by matthewroche** [EdgeApp/react-native-fast-crypto#12]
Hi,

I am trying to implement your version of PBKDF2 as it is the only one I can find that allows modification of key length and iterations. I am new to cryptography, so apologies if my question is inappropriate.

Could you clarify whather your PBKDF2 function requires the password and salt to be input as Uint8Arrays (as suggested here: https://github.com/Airbitz/react-native-fast-crypto/blob/master/index.js) or as strings?

Could you also clarify the format of the output?

Perhaps these details could be added to the readme?

Thanks

**Comment by swansontec** [comment]
Here is the type definition for the function, taken from another library of ours that uses it:

```typescript
export type EdgePbkdf2 = {
  deriveAsync: (
    key: Uint8Array,
    salt: Uint8Array,
    iter: number,
    len: number,
    algo: string
  ) => Promise<Uint8Array>
}
```

So yes, it looks like it's `Uint8Array` all around. You need a function to convert strings to this format.

**Comment by matthewroche** [comment]
@swansontec That's exactly what I was looking for. Thank you. I'll close the issue.
