### ISSUE TITLE
Has this library been tested against other scrypt libraries?

### ISSUE THREAD

**Issue by Vanclief** [EdgeApp/react-native-fast-crypto#18]
I am implementing the [warpwallet address generator](https://keybase.io/warp/warp_1.0.9_SHA256_a2067491ab582bde779f4505055807c2479354633a2216b22cf1e92d1a6e4a87.html) in a react native which utilizes scrypt.

So for that I have the following line of code where I am using this library.

```
import fcrypto from 'react-native-fast-crypto';
...
let s1 = await fcrypto.scrypt(passphrase + '\x01', salt + '\x01', 262144, 8, 1, 32)
```

However this returns a completely different Buffer than the one obtained from other libraries with exactly the same params. I tested it against:

1. https://github.com/barrysteyn/node-scrypt
2. https://github.com/cryptocoinjs/scryptsy

**Comment by paullinator** [comment]
It is compatible with other scrypt libraries but the doc might be out of date. The scrypt routine accepts a Uint8Array, not a string. Give that a try.

**Comment by Vanclief** [comment]
Hey Paul, thanks for the quick answer.

A Unint8Array for both secret and salt params? If you could provide an example, that would be great.

**Comment by paullinator** [comment]
Updated readme with correct examples using Uint8Array. Sorry readme had string based examples from before we shipped the first production version of this library.

https://github.com/EdgeApp/react-native-fast-crypto/commit/b5fd9bed9b1da92d800da808036869161a790e64
