### ISSUE TITLE
android is returning undefined

### ISSUE THREAD

**Issue by nomoreboredom** [EdgeApp/react-native-fast-crypto#4]
On android, if debug mode is off, the package is not completing the return. It fails on this slice:

```return uint8array.slice(0, size)```

However uint8array is created properly.

**Comment by paullinator** [comment]
What nondebug environment are you running this under? uint8array does need to be available and provide the slice() method. In our testing this works on Android as the RN packager provides a polyfill for uint8array.

**Comment by nomoreboredom** [comment]
On IOS with Android Studio emulator, when regular RN debugger is off I meant. RN version I am using is alike yours @0.47.  

After your comment, I checked and read in a couple of S.O. questions that: 

```TypedArray.prototype.slice()```  

is not supported in some env.

However, returning ```return uint8array.subarray(0, size)``` works on both IOS and Android. Do you perhaps see any quirks using subarray instead of slice?

Thanks for the repo btw!

**Comment by paullinator** [comment]
Sorry for the late response. Let me look into it's use and see if subarray can work. I'm surprised slice() isn't available

**Comment by paullinator** [comment]
Yep, it looks like subarray should work just fine. I'll look at making that change in the next major release.
