### ISSUE TITLE
Question: Why is it possible to define data types in js

### ISSUE THREAD

**Issue by WuChenDi** [EdgeApp/react-native-fast-crypto#45]
Hi guys, I have a question, why do I see in `index.js` that I can declare data types, won't that be a problem?

If this is possible, what `Loaders` should I be using in webpack to parse it?

I currently have the following problem with generating umd for packaging：
<img width="905" alt="image" src="https://user-images.githubusercontent.com/31385662/184533072-55af2755-7570-4d13-aeec-f96c2584f1a1.png">

**Comment by paullinator** [comment]
This is a bit of an oversight. Our RN app uses Flow for type checking which uses `.js` files. Admittedly the file should have

`// @flow` 

at the top to signify this but it was left out. This whole project should be converted to Typescript which is what we are using going forward.

**Comment by WuChenDi** [comment]
@paullinator Thank you for your reply, so is there any way to solve my problem now?

**Comment by paullinator** [comment]
Easiest thing is to remove the types for now. It's a small file so it should be easy. @WuChenDi

**Comment by WuChenDi** [comment]
OK, I got it, thank you.

Looking forward to using `typescript` in the future.

The issue is closed.

**Comment by hazim-j** [comment]
I also had this problem too since our react-native codebase is written in typescript. My current solution is to use [patch-package](https://github.com/ds300/patch-package) to convert `index.js` to `index.ts`. For anyone else coming across this issue this is the exact patch I'm using:

```patch
diff --git a/node_modules/react-native-fast-crypto/index.js b/node_modules/react-native-fast-crypto/index.ts
similarity index 89%
rename from node_modules/react-native-fast-crypto/index.js
rename to node_modules/react-native-fast-crypto/index.ts
index 3dbf764..7c9f251 100644
--- a/node_modules/react-native-fast-crypto/index.js
+++ b/node_modules/react-native-fast-crypto/index.ts
@@ -23,15 +23,12 @@ async function pbkdf2DeriveAsync(
   return base64.parse(out, { out: Buffer.allocUnsafe })
 }
 
-export async function scrypt(passwd, salt, N, r, p, size) {
-  passwd = base64.stringify(passwd)
-  salt = base64.stringify(salt)
-
+export async function scrypt(passwd: ArrayLike<number>, salt: ArrayLike<number>, N: number, r: number, p: number, size: number) {
   console.log(
     'RNFS:scrypt(' + N.toString() + ', ' + r.toString() + ', ' + p.toString()
   )
   const t = Date.now()
-  const retval: string = await RNFastCrypto.scrypt(passwd, salt, N, r, p, size)
+  const retval: string = await RNFastCrypto.scrypt(base64.stringify(passwd), base64.stringify(salt), N, r, p, size)
   const elapsed = Date.now() - t
   console.log('RNFS:script finished in ' + elapsed + 'ms')
 
diff --git a/node_modules/react-native-fast-crypto/package.json b/node_modules/react-native-fast-crypto/package.json
index 86ba5fc..4c6631d 100644
--- a/node_modules/react-native-fast-crypto/package.json
+++ b/node_modules/react-native-fast-crypto/package.json
@@ -19,7 +19,7 @@
     "Paul Puey <paul@edge.app>",
     "William Swanson <william@edge.app>"
   ],
-  "main": "index.js",
+  "main": "index.ts",
   "files": [
     "/android/build.gradle",
     "/android/jni/*",

```

This should unblock you until the team releases a typescript update. _Till then, props to the team for building this open-source library and providing fast crypto functions in react-native! (sorely needed imo)_

**Comment by WuChenDi** [comment]
@hazim-j You're doing a great job.
The way I handled it the other day was rather dumb, I copied the repository down and modified the source code, then posted it to a private npm to use
