### ISSUE TITLE
[Android] Undefined is not a function (evaluating 'f.slice(0,s)')

### ISSUE THREAD

**Issue by terriblywasted** [EdgeApp/react-native-fast-crypto#6]
I have following issue:

Your sample code in react-native blank app throws an error `Undefined is not a function (evaluating 'f.slice(0,s)')` in android environment (release build)
```
const p = crypto.scrypt('mypassword', 'mysalt', 16384, 8, 1, 32)
p.then((result) => {
  console.log(result)
}, (error) => {
  console.log(error)
})
```

The same issue already closed (#4), why? 

------

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v8.9.0
5.5.1
fastcrypto@0.0.1 /Users/slava/Projects/workbook/fastcrypto
├── react@16.2.0
├── UNMET PEER DEPENDENCY react-native@0.52.0
└── react-native-fast-crypto@1.5.3
```

**Steps to reproduce**

- react-native init myproject
- npm i react-native-fast-crypto
- react-native link
- add your sample code to app.js
- *sign app*
- cd android && ./gradlew assembleRelease
- install app on device or emulator

**Comment by swansontec** [comment]
Ah, the reason this happens is because React Native has a really old version of Javascript on Android, which is missing some important polyfills. Our Edge Wallet app does some things to patch & upgrade the Javascript environment (including adding the Uint8Array.slice method).

**Comment by swansontec** [comment]
We should go ahead and fix the core not to do this. In the meantime, just run the following polyfill code once your app launches to fix the issue:

```js
if (!Uint8Array.prototype.slice) {
   Uint8Array.prototype.slice = function slice (start, end) {
     return new Uint8Array(Array.prototype.slice.call(this, start, end))
   }
}
```

**Comment by paullinator** [comment]
This is fixed with https://github.com/EdgeApp/react-native-fast-crypto/commit/9dca5e47f403b74c7b5de35023d35f39b9c579ec
