### ISSUE TITLE
Is the interface the same as the nodejs native crypto module?

### ISSUE THREAD

**Issue by DaniGuardiola** [EdgeApp/react-native-fast-crypto#7]
Could this be used as a drop-in replacement? Is the security comparable?

Thanks :)

NodeJS crypto: https://nodejs.org/api/crypto.html

**Comment by paullinator** [comment]
No it can't. Primarily because the nodejs interface is synchronous but calling native code from RN requires async calls. We'll also be adding routines that nodejs doesn't support. I'll try to keep them similar, but don't expect a drop in replacement.
