### ISSUE TITLE
Failed to build in xcode due to "does not contain bitcode"

### ISSUE THREAD

**Issue by TerenceGe** [EdgeApp/react-native-fast-crypto#9]
Hello, I'm trying to integrate this lib into my RN project. 
It works fine in debug mode. But when I build in release mode, it shows me the following error:

libRNFastCrypto.a(native-crypto.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Do I have to disable bitcode for this lib?

Xcode version: 9.3.1
React Native version: 0.53.0

**Comment by paullinator** [comment]
Yes. Pls try with bitcode disabled.

**Comment by TerenceGe** [comment]
Ok, it works.

**Comment by lukasa1993** [comment]
no chance this can support bitcode ?
